version: '3.8'

services:
  backend:
    build: ./Backend/.
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./Backend/.:/usr/src/app/backend
    command: air cmd/main.go -b 0.0.0.0

  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data3
  frontend:
    build: ./estudiantica/.
    env_file:
      - .env
    ports:
      - 3001:3001
    volumes:
      - ./frontend/.:/usr/src/app/frontend
    command: npm run dev
volumes:
  postgres-db:
