name: Validate Source Branch is Develop for Pull Requests to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Pull Request Source Branch
        env:
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          DEST_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "Source branch: $SOURCE_BRANCH"
          echo "Destination branch: $DEST_BRANCH"
          if [ "$DEST_BRANCH" = "main" ] && [ "$SOURCE_BRANCH" != "develop" ]; then
            echo "Pull requests to main branch are only allowed from develop branch."
            exit 1
          fi
